const languages = {
    english: {
        heroHeader: <>Hello!<br/>I am <span>Maciej Walecki.</span></>,
        heroText: 'Junior frontend developer from Poland.',
        cvButton: 'Download Resume',
        aboutMeHeader: 'About me',
        aboutMeText: `I'm 22 years old student of gastronomy and hotel managment from Warsaw (Poland). Because of the gastronomy lockdown due to the covid-19 pandemic I decided to change my carrier path and try myself in coding.`,
        skillsText: 'In that time I learned this technologies:',
        myProjectsHeader: 'My projects',
        myProjectsText: 'Here are some of the projects I made while I was learning to code.',
        rockPaperScissorsDescription: 'This app is the copy od classic rock, paper and scissors game.',
        cocktailsAppDescription: 'App where You can search for a specific cocktail, and check its recipe.',
        contactMeHeader: 'Contact me!',
        contactMeText: 'You can contact with me here throught this form. You can also find me on social media like: Facebook, LinkedIn and GitHub.',
        contactTextbox: 'Enter your message here...',
        contactSuccessfull: 'Your message has been sent!',
        contactFailed: 'Something went wrong.',
        contactSend: 'Send',
    },
    polish: {
        heroHeader: <>Witaj!<br/>Jestem <span>Maciej Walecki.</span></>,
        heroText: 'Junior frontend developer.',
        cvButton: 'Pobierz CV',
        aboutMeHeader: 'O mnie',
        aboutMeText: `Jestem 22 letnim studentem gastronomii i hotelarstwa z Warszawy. Z powodu lockdown'u gastronomii przez pandemię zdecydowałem się zmienić moją ścieżkę zawodową i zacząć uczyć się pisać strony internetowe.`,
        skillsText: 'Przez ten czas nauczyłem się następujących technologii:',
        myProjectsHeader: 'Moje projekty',
        myProjectsText: 'Tutaj są niektóre z projektów które wykonałem podczas nauki kodowania.',
        rockPaperScissorsDescription: 'Aplikacja będąca odwzorowaniem klasycznej gry w papier, kamień, nożyce.',
        cocktailsAppDescription: 'Aplikacja w której można wyszukać konkretny koktajl, oraz zobaczyć na niego przepis.',
        contactMeHeader: 'Skontaktuj się ze mną!',
        contactMeText: 'Możesz skontaktować się ze mną tutaj przez formularz. Można mnie także znaleźć na mediach społecznościowych takich jak: Facebook, LinkedIn i GitHub.',
        contactTextbox: 'Tutaj wpisz Twoją wiadomość...',
        contactSuccessfull: 'Twoja wiadomość została wysłana!',
        contactFailed: 'Coś poszło nie tak.,',
        contactSend: 'Wyślij',
    },
};

export default languages;